### ISSUE TITLE
Cross-Breeding to create new species not working.

### ISSUE THREAD

**Issue by Nehound** [CreeperHost/Chickens#10]
Hi guys,
Been really enjoying the 1.18.2 version of this mod in a recent 1.18.2 playthrough I've been doing with some friends. However, when I have been trying to breed the base chickens (Flint, Log, Bone White etc) I'm not able to breed any of the hybrid kinds (iron, gunpowder etc). At first, I thought the drop rate may just be super low, but after breeding well over 100 chickens with none of the hybrids I suspect something is up>

Anyone able to help or maybe know a fix?

Thanks all!

**Comment by gigabit101** [comment]
Are you sure you are breeding the correct chickens, look in JEI for the correct combination as this is working just fine for me
