### ISSUE TITLE
Suggestion: Document usage of Chicken Catcher

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/Chickens#11]
Relayed from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1288

A player was confused when using the Chicken Catcher to try and catch a chicken:

> Ok, so the Chickener Catch DOES work. you have to hit a chicken with a Book first...
> This should be noted in game, or a wiki or something...

I could suggest a JEI information tab, a tooltip, or a Patchouli book if you want to be fancy :^) Resourceful Bees had a similar thing with a book and it was neat. I can help with the book if you want to take that route. I've done some Patchouli books before (though never within a mod). Let me know!

**Comment by gigabit101** [comment]
I think I added this in the 2.0 version already but will make a note to make sure

**Comment by Nicon4454** [comment]
ok so how does the catcher work? do i right click the chicken with a book first then right click with the chicken catcher?

**Comment by xaelith** [comment]
> ok so how does the catcher work? do i right click the chicken with a book first then right click with the chicken catcher?

The chicken in question has to be a "Chickens" mod chicken, but otherwise, you just right-click with the chicken catcher. If the chicken is a vanilla or vanilla-esque chicken, right-clicking with the book changes them to a "Smart Chicken", which then can be interacted with using the chicken catcher.

**Comment by Nicon4454** [comment]
Ok thank you that helps 

Don't only practice your art, but force your way into its secrets; art deserves that, for it and knowledge can raise man to the Divine. 

— Ludwig van Beethoven
