### ISSUE TITLE
Dupe Bug with Roost

### ISSUE THREAD

**Issue by UnRealDinnerbone** [CreeperHost/Chickens#13]
When the Roost output is full and the progress bar is maxed out, and then you start outputting, the progress bar never resets, and it keeps putting more and more resources into the output without needing to wait https://s.dinnerbeef.com/gOXe5/hufIBEkE60.mp4/raw

Version: 1.18.2-1.0.7

**Comment by gigabit101** [comment]
huh, will fix tomorrow
