### ISSUE TITLE
Can see though Breeder block

### ISSUE THREAD

**Issue by UnRealDinnerbone** [CreeperHost/Chickens#14]
You can see though the Breeder block 

https://unreal.codes/2022/9/19/javaw_vOAKKvC8sg.png

Version: 1.18.2-1.0.7

**Comment by gigabit101** [comment]
Might want to check that screenshot lol

**Comment by UnRealDinnerbone** [comment]
woops https://unreal.codes/2022/9/19/javaw_TvLut1inml.png
