### ISSUE TITLE
Breeder puts new chickens in breeding slots

### ISSUE THREAD

**Issue by UnRealDinnerbone** [CreeperHost/Chickens#18]
When breading, for example, two 10 10 10 Iron chickens it puts them in the slot for breading, meaning that you cant automate breading of new chickens (take them out auto), they should be going in the output slot

https://unreal.codes/2022/9/23/javaw_l6LOM1uMw1.mp4

Version: 1.18.2-1.0.10

**Comment by gigabit101** [comment]
Fixed in 1.0.20, Now available on CurseForge
