### ISSUE TITLE
Water/Lava Eggs not functioning

### ISSUE THREAD

**Issue by JacobToroTime** [CreeperHost/Chickens#2]
I'm not sure if this is just me or not, but every attempt to use the water and lava eggs has failed. If anyone else has had this issue, please let me know- alternatively, if water/lava eggs are just planned, with the items as placeholders, also let me know.  I have the architecturey api and Polylib by creeperhost installed, along with of course the mod itself, all on 1.18.2. Downloaded/installed mod through curseforge launcher, if that helps.

Many thanks!

**Comment by gigabit101** [comment]
This should have been fixed in the latest 1.19 version
