### ISSUE TITLE
Suggestion: A bit OP?

### ISSUE THREAD

**Issue by InfinitysDaughter** [CreeperHost/Chickens#22]
I absolutely love the mod, so glad to have my chickens back in 1.19.

But I've noticed that when breeding a new resource the child automatically gains the stats of its parents if maxed or increase the stats in the child and its crazy easy to breed up to 10/10/10 on T1 resources. You get top stats on top tiers very quickly which is nice that you dont have to worry about resources but kinda removes the challenge when you can get 1k in diamond blocks after a few hours of play. Even in modded lol.

Might consider tweaking how stats get passed down? Maybe set the new resource to minimum stats when its produced via breeding? Or lowering the chance of stats increasing in the next generation?

Up to you, obviously. Just my two cents. ^_^

**Comment by gigabit101** [comment]
That was a bug, Fixed in Dev

**Comment by gigabit101** [comment]
Fixed in 1.0.20, Now available on CurseForge
