### ISSUE TITLE
Hoppers/Pipes pull from input slots on Breeder

### ISSUE THREAD

**Issue by zerofall** [CreeperHost/Chickens#23]
When I try to extract the output "bred" chickens from the Breeder using a Hopper or pipes, it pulls the "breeding" chickens out of the input slots.

Modpack: Stoneblock 3, 1.0.0

**Comment by zerofall** [comment]
Im guessing this would fix it?
`BlockEntityRoost.java`
``` java
@NotNull
@Override
public ItemStack extractItem(int slot, int amount, boolean simulate)
{
    // Slots 0 and 1 are for breeding chickens, Slot 2 is for seeds. Don't extract these.
    if(slot <= 2) return ItemStack.EMPTY;
    return super.extractItem(slot, amount, simulate);
}
```

**Comment by gigabit101** [comment]
Fixed in .23, Should show up on Curse soon
