### ISSUE TITLE
Suggestion: More Localization Support

### ISSUE THREAD

**Issue by StarskyXIII** [CreeperHost/Chickens#24]
Currently, some tooltips and JEI categories can't not be translated.

Hold Shift for stats
![image](https://user-images.githubusercontent.com/71606873/199641677-d29fcbfe-bc62-4ce5-8289-e2a02a7937b6.png)

Chicken Stats
![image](https://user-images.githubusercontent.com/71606873/199641724-d24f2227-80bf-4859-8762-83b7e428d76e.png)

JEI categories
![image](https://user-images.githubusercontent.com/71606873/199641899-7dfdc8a3-a094-40a8-9e5e-4e8b22919fa7.png)

**Comment by gigabit101** [comment]
Fixed in .24, Should be live on CurseForge soon

**Comment by gigabit101** [comment]
If you wish to provide me with the updated localisation file I will merge it for the next release
