### ISSUE TITLE
Suggestion: Breeder speed mechanics from Roost

### ISSUE THREAD

**Issue by MegaHakkero** [CreeperHost/Chickens#25]
The breeder in the original roost mod for 1.12.2 gets faster based on how many chickens you put into the breeding slots and what their growth level is. Will this mechanic be ported later?

**Comment by halvalla01** [comment]
I feel like more people would like this. Having 10-10-10 chickens breed just as fast as 1-1-1's is quite frankly stupid and a tiny bit annoying
