### ISSUE TITLE
Lava egg deletes blocks

### ISSUE THREAD

**Issue by BeeIsYou** [CreeperHost/Chickens#27]
(version 1.0.24, using FTB Stoneblock 3)
Use it on the surface of an adjacent block sharing a side with the block to be deleted
![2022-11-05_20 04 59](https://user-images.githubusercontent.com/32610465/200119048-3eba6f30-1e25-407c-afa3-3d073c03cfe4.png)
![2022-11-05_20 05 01](https://user-images.githubusercontent.com/32610465/200119058-e34b74cc-c46a-4a7b-9288-78dfbc78c47b.png)
![2022-11-05_20 05 04](https://user-images.githubusercontent.com/32610465/200119062-aed8eb33-4628-4c71-93e0-9e0a50b4312c.png)
It also doesn't act like a lava bucket, you can't place it into the tank of any mod

**Comment by gigabit101** [comment]
fixed in .26
