### ISSUE TITLE
Documentation and Configuration issue: Posted mod states breeding times can be adjusted. Configuration does not show this.

### ISSUE THREAD

**Issue by FishyPlays** [CreeperHost/Chickens#28]
I do not see any documented listing in the configuration file(chickens.json) that allows for the speed of breeding to be adjusted. Breeding is a touch on the slow and tedious side as it stands at present, it would be nice to be able to edit that in config, and I don't see an option to do so, nor documentation on HOW to do so.

**Comment by gigabit101** [comment]
Currently this is not configurable
