### ISSUE TITLE
Roosts Exceed Maximum stack size

### ISSUE THREAD

**Issue by tyler489** [CreeperHost/Chickens#29]
When putting a stack of 16 10/10/10 Smart chickens in a roost, the slots fill with 48 eggs per slot, when the default stack size for eggs is 16.

**Comment by tyler489** [comment]
I saw this commit https://github.com/CreeperHost/Chickens/commit/e05a7838de8d70d7d37a74d76e2fd258bcf7a786 but that seems to only apply if a partial stack already exists? I could be wrong.

**Comment by gigabit101** [comment]
fixed in .26
