### ISSUE TITLE
Massive hitboxes on modded chickens

### ISSUE THREAD

**Issue by tyler489** [CreeperHost/Chickens#31]
It seems chickens have a ~1.8 block tall hitbox, like a zombie or creeper, as opposed to a smaller hitbox that would fit their size, like a vanilla chicken. https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1746
![2022-11-07_16 24 42](https://user-images.githubusercontent.com/7015040/200429140-479d0742-d67f-4407-871e-2b4dc3352a72.png)

**Comment by gigabit101** [comment]
fixed in .26
