### ISSUE TITLE
Chicken Roosts Crash instantly joining server

### ISSUE THREAD

**Issue by Sunekaer** [CreeperHost/Chickens#33]
### Describe the bug

_When joining the server im playing on I crash almost instantly. Happened after updating from version 1.0.2 to 1.2.0_

https://github.com/FTBTeam/FTB-Modpack-Issues/files/9983615/crash-2022-11-09_22.03.05-client.txt
https://github.com/FTBTeam/FTB-Modpack-Issues/files/9983712/2022-11-09-1.log

**Comment by gigabit101** [comment]
Fixed in 1.0.28
