### ISSUE TITLE
Bug: Lava and Water eggs dont place on top of flowing liquid blocks

### ISSUE THREAD

**Issue by IlmarsXd** [CreeperHost/Chickens#34]
When trying to place a water egg on flowing water, it does not place, same with the lava eggs. Placing lava on water/water on lava does the same.

**Comment by gigabit101** [comment]
Eggs require you to click on a solid block to use currently. This is technically a bug but low priority

**Comment by gigabit101** [comment]
Fixed in 1.0.29
