### ISSUE TITLE
[1.19] REI does not show recipes for upgrading chickens

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/Chickens#4]
Currently JEI isn't on 1.19 but REI is, however the entire chicken upgrading category does not show in REI. The integration does work in 1.18.2 with REI so I'm not sure what's broken. JEI hasn't ported to 1.19 yet so I cant test it with jei.

**Comment by MaxNeedsSnacks** [comment]
FWIW, since REI also implements the most recent version of the JEI API at the time of writing, it should be possible to just rely on that as a compile time dependency for now

**Comment by gigabit101** [comment]
JEI was not available when porting this over so currently jei compat is commented out, I will add it back once JEI is released

**Comment by gigabit101** [comment]
Fixed in 1.0.6

**Comment by FearAK** [comment]
Hello, I'm using the latest version of the chickens mod for 1.18 and latest rei version and there is no recipe for upgrading chickens
