### ISSUE TITLE
No Recipes on 1.19.2

### ISSUE THREAD

**Issue by Nicon4454** [CreeperHost/Chickens#41]
Mod Version: 1.19.02-1.0.8
there are no crafting or breading recipes for the following chickens
Sand, Nether Quartz, Log, Flint, and Soul Sand. I hope I did not miss any. if KubeJS is installed this is a work around. just place the file in yourmodpack/kubejs/server_scripts/ and then change the ext from .txt to .js
[chickens.txt](https://github.com/CreeperHost/Chickens/files/10229152/chickens.txt)

**Comment by EnderiteFox** [comment]
It's normal that these chickens don't have a craft. They are spawning naturally, and they are the starting point to craft other chickens, you just have to find them

**Comment by Nicon4454** [comment]
ok then should i remove the recipes file from my original post?

**Comment by EnderiteFox** [comment]
Yes, you don't really need them, the chickens are pretty common
