### ISSUE TITLE
Game won't even boot up

### ISSUE THREAD

**Issue by DarkWolfyy21** [CreeperHost/Chickens#42]
I tried installing the chickens mod into a modpack, and when I booted up my whole screen was that pink and black no texture block. Game crashed right after that with this error message:

The game crashed whilst rendering overlay
Error: java.lang.IllegalAccessError: failed to access class net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing from class net.mehvahdjukaar.modelfix.ModelFix (net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing is in module minecraft@1.19.2 of loader 'TRANSFORMER' @5f0f70c7; net.mehvahdjukaar.modelfix.ModelFix is in module modelfix@1.8 of loader 'TRANSFORMER' @5f0f70c7)

This is using the 1.19.2 version of the mod.

**Comment by SMSchepke** [comment]
What was the solution to this problem? I'm having the exact same issue.

**Comment by xaelith** [comment]
Based on the error line `from class net.mehvahdjukaar.modelfix.ModelFix`, it looks to me that another mod and the Chickens mod are clashing. Googling "model fix mod" brings up a mod called "Model Gap Fix", which I'm assuming is the offender.

I don't know what is causing the two mods to not like each other specifically, but I would bring up the issue with them as well.

**Comment by SMSchepke** [comment]
Thank you so much. I'll dig into that.
