### ISSUE TITLE
Extracting from input slots

### ISSUE THREAD

**Issue by shubidubapp** [CreeperHost/Chickens#43]
I am not sure what I would categorize this issue as, it might both be a simple question or suggestion. So I am sorry if the structure of this issue is subpar. 

I see that extracting chickens from input slots is purposefully blocked with the issue #23, at least this is what I understand from the suggested change and the content of the issue. But as a result it is impossible to automate breeding using only 1 Breeder, except for breaking and re putting the block itself which I think is not a valid solution. I understand the need to block unwanted pulls. 

Since I am not a mod developer myself, this may not really be a possible solution but could we make it so we can pull all slots (0 to 5?) from the left side of the block(as an example) or somehow dynamically enable or disable the change in #23 ? There are a lot of mods that are using side configurations for input and output access, there are mods that can specifically pull from/push to different sides of the blocks while touching only one side(like LaserIO) or even mods that can do that only on selected inventory slots(like ComputerCraft-CC Tweaked) I think this would be a solution for both #23 and my issue.

**Comment by EliasRLima** [comment]
I also consider the lack of this slot a problem, there are ways to solve this but they all involve using external mods to break the block. I believe that the ideal would really be a slot or block that is a little close and is able to control them.

My ideal way I think: seed slot accessible from the top, add/remove parents from the sides and "children" can be removed from the bottom

**Comment by gigabit101** [comment]
There are a LOT of mods that do no allow you to pull from the input slot, Right now I have no intention on changing this as there needs to be some sort of "balance", Making this a manual process for now works.
You are always free to write an addon adding an advanced version of the breeder block
