### ISSUE TITLE
All Renders Go Bye Bye

### ISSUE THREAD

**Issue by manmaed** [CreeperHost/Chickens#46]
**Log Files**
Crash Report: https://pste.me/@/pRBcah7vl0I
Latest: https://pste.me/@/ZMXrA42xVB8
Debug: https://pste.me/@/NkLBrj-_08k
**Bug Description**
Renders go bye bye when looking in creative disks
**Steps to reproduce**
get gaz cheaty disk
get nul1 from chickens
get all items render now and crash
**Expected behaviour**
for renders not go bye
Mods Invoved:
Creative Disk
Chickens
Refined Storage

Confirmed with:
Forge: 43.2.4
Architectury 6.5.69
Chickens: 1.0.8
Cloth Config v8 API: 8.2.88
Creative Disk: 1.0.0+mc1.19.2
PolyLib: 1900.0.2-build.42
Refined Storage: 1.11.5
REI: 9.1.591

**Comment by gigabit101** [comment]
Fixed in 1.19.2-1.0.30
