### ISSUE TITLE
[1.19] Chickengeddon still present (overspawning)

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/Chickens#5]
In the latest version the chicken spawn rates do not seem to be fixed. They seem to be ignoring any sort of mob cap so they keep spawning until we clear them with a command. They also spawn in the mining dimension where passive spawning is completely disabled.

![download](https://user-images.githubusercontent.com/9200909/174682331-5aa153a2-949a-4423-963b-bf631c134a0c.png)

**Comment by MaxNeedsSnacks** [comment]
Also, Chickens are spawning in the Mining Dimension, which are supposed to have **no** natural mob spawns

**Comment by gigabit101** [comment]
Fixed in latest release
