### ISSUE TITLE
Soul Chickens

### ISSUE THREAD

**Issue by penturt** [CreeperHost/Chickens#50]
IS there a certain biome of the Nether that Soul Chicken are found? I have been looking for them for hours and have had no luck.

**Comment by Saereth** [comment]
This was reported by a couple others, no chickens spawning in the nether. I loaded up just chickens and vanilla and flew around for a bit in the nether. I didnt find any quartz chickens either.

**Comment by gigabit101** [comment]
Minecraft versions and Mod versions?

**Comment by penturt** [comment]
I'm using chickensmod-1.19.2-1.0.30, on forge 1.19.2 - 43.2.6

**Comment by xaelith** [comment]
Depending on the modpack, there may be a crafting recipe for the egg or chicken, as well. Both soul sand and quartz chickens are listed as "nether spawn" in FTB One, yet the egg to spawn them can be crafted, and few if any chickens were spawning for me in the Nether.

**Comment by Saereth** [comment]
> Minecraft versions and Mod versions?

MC 1.19.2
Forge 43.2.6
Modpack: FTB One 2.2.0 (other versions also effected)
Chickensmod: 1.0.30

**Comment by gigabit101** [comment]
Fixed in .32
