### ISSUE TITLE
How to fix broken textures?

### ISSUE THREAD

**Issue by xaelith** [CreeperHost/Chickens#51]
![Broken texture custom chickens](https://user-images.githubusercontent.com/62457551/226160158-a666c8a0-9d16-4680-bf44-7d8e0823aeb2.png)

As shown in the attached photo, several of the custom chickens I created display with the "broken texture" texture. How do I add the appropriate texture? If this isn't currently possible, could a line be added in the config of a future version to allow custom textures?

**Comment by gigabit101** [comment]
You can add custom textures via a resource pack, I would recommend looking at StoneBlock3 and how they handled adding custom chickens
