### ISSUE TITLE
Unable to set parents for Nether Quartz Chicken

### ISSUE THREAD

**Issue by brad811** [CreeperHost/Chickens#54]
Setting the parents for "chickens:quartz_chicken" in the chickens.json config file does not work. I was trying to work around chickens not spawning in the nether (https://github.com/CreeperHost/Chickens/issues/50), and was able to set parents for "chickens:soulsand_chicken", but was not able to breed a quartz chicken, and checking JEI confirms there is no recipe for quartz chickens.

Works:
```
"chickens:soulsand_chicken": {
    "name": "soulsand_chicken",
    "is_enabled": true,
    "lay_coefficient": 1.0,
    "lay_item": {
      "itemID": "minecraft:soul_sand"
    },
    "drop_item": {
      "itemID": "minecraft:soul_sand"
    },
    "spawn_type": "HELL",
    "parent_1": "chickens:white_chicken",
    "parent_2": "chickens:sand_chicken"
  }
```

Does not work:
```
"chickens:quartz_chicken": {
    "name": "quartz_chicken",
    "is_enabled": true,
    "lay_coefficient": 1.0,
    "lay_item": {
      "itemID": "minecraft:quartz"
    },
    "drop_item": {
      "itemID": "minecraft:quartz"
    },
    "spawn_type": "HELL",
    "parent_1": "chickens:white_chicken",
    "parent_2": "chickens:soulsand_chicken"
  }
```

**Comment by xaelith** [comment]
As far as I can tell, that **_should_** work. Maybe try swapping the parent1 and parent2 chickens and see if that helps? Also, make sure to check both the spawn egg **_and_** the chicken for a recipe; sometimes the crafting recipe shows for one but not the other.

Otherwise, I can try running some tests, but won't be able to do so until my weekend starts (due to this annoying thing called "work", and all that 😉 ).

**Comment by brad811** [comment]
Thanks for the suggestions!

I tried that, and it didn't seem to work (I checked the egg for recipes as well).

So I tried some tests, and one was to set both parents of every parentless chicken to both be "chickens:sand_chicken".
The ONLY one that worked was the soul sand chicken! All others still had no recipe, egg or chicken. (The only eggs I see are the 15 dye chicken eggs)

I made a mod pack just for this test to eliminate variables. Here's what I'm running:
Minecraft 1.19.2
Forge 43.2.0
MCP 20220805.130853
Just Enough Items 11.6.0.1013
Chickens 1.0.30

Let me know if you need any more info!

(TODO: PR to remove this "work" thing)

**Comment by brad811** [comment]
Minor correction: I see all the eggs (I was searching for the word "egg" but only the dye eggs have that in their name), but none of them but the dye eggs have recipes with the above config change.

**Comment by xaelith** [comment]
What modpack are you playing/trying to play?

**Comment by brad811** [comment]
I've been working on my own modpack that has 30+ mods for fun, so I made a new one with only JEI and Chickens to isolate this issue.

**Comment by xaelith** [comment]
Gotcha. I've been dabbling with FTB One, myself, which includes KubeJS. Somewhere in the kubejs folder is a chickens.js file in a recipe/recipes folder, and that's what actually adds the recipes for the spawn eggs. However, if you're wanting to avoid adding another mod, the same can be done using datapacks.

**Comment by brad811** [comment]
That works as a workaround, thank you!

**Comment by patonz** [comment]
any update?

**Comment by gigabit101** [comment]
Created a test recipe using the json with no issues 
![image](https://user-images.githubusercontent.com/5615438/235937046-26af5256-dc6a-4fa8-940f-3538fa15b1a8.png)

**Comment by gigabit101** [comment]
If you are still having this issue with the latest version please provide me with your config file
