### ISSUE TITLE
Soul Chicken does not have feet texture

### ISSUE THREAD

**Issue by UnRealDinnerbone** [CreeperHost/Chickens#55]
Minecraft: 1.18.2

Mod Version: 1.0.30

Issue: The soul chicken does not have a leg texture

![image](https://user-images.githubusercontent.com/8102498/234971814-07bdf908-114e-453d-8131-a4d6e72f8644.png)

**Comment by gigabit101** [comment]
Not a rendering issue, the texture file does not have feet, these are the original textures from the original author
