### ISSUE TITLE
Chickens don't drop materials in 1.18.2

### ISSUE THREAD

**Issue by hyygybs** [CreeperHost/Chickens#61]
Chickens version 1.0.31
When i killed a mod chicken, it only drop chicken and feather.
And drop item is same as lay item in jei when i have changed it in config.

**Comment by xaelith** [comment]
> ...When i killed a mod chicken, it only drop chicken and feather...

This is the correct behavior. The "drop item" config only changes what the chickens "drop" naturally, not what is dropped when they are killed. Instead of dropping an egg as a vanilla chicken will do, they drop the item specified in the config after a few minutes real-time. 

Hope this helps 😃
