### ISSUE TITLE
Lava and Water egg interactions

### ISSUE THREAD

**Issue by penturt** [CreeperHost/Chickens#63]
Does anyone know of machines/block that interact with the water or lava egg which actually act like buckets? dispenser don't pour the fluid out like if was a bucket. and i can't find any machine or pipes from mod that pull it out like a fluid either. Maybe add a block into the mod that converts the water or lava eggs into a fluid container of sorts? or a bucket type so automation would be possible.

**Comment by xaelith** [comment]
This is the same as #59. I was able to get it to work using the Cyclic item user and a small Refined Storage network. I also had to make sure fake players were enabled. I'll add a reply with screenshots as soon as I'm able.

**Comment by penturt** [comment]
Ahhh of course cyclic, not a fan of that mod, gonna try using the clicking machine mod

**Comment by xaelith** [comment]
Just out of curiosity, what don't you like about cyclic? I admit there are issues, such as no documentation for how a lot of the "machines" work.

In any event, whatever you use, make sure fake players are allowed. 😉

**Comment by penturt** [comment]
It's like half and half, I like parts of it. The machines are really the part I don't like. But in all honesty I can't pin point what it is about it.

**Comment by xaelith** [comment]
I get you. There are definitely quirks that make working with it difficult, such as the Solidification Chamber sometimes requiring an exact amount of liquid with one recipe, and then using any amount of fluid with another.

I'm the same way with Create and Immersive Engineering, myself. Functionally, there is nothing wrong with those two mods, and the aesthetics more closely match with vanilla, but I find it a grind when I'm forced to use either of them in a modpack. I think a lot of that comes to not liking how much space is required for those two mods to work well.

**Comment by xaelith** [comment]
For any others wanting to replicate my setup, pictures/instructions below:

[Basic Setup](https://www.dropbox.com/scl/fi/zcck18u3nhftha6g8cc1y/Basic-setup-overview.png?rlkey=pm5bxuc98d3zpkbe8yd9uxh4k&dl=0) - Screenshot showing most of the setup.
[Item User](https://www.dropbox.com/scl/fi/bn3rlpdmlpmqou9l999f8/Item-User-settings.png?rlkey=xapptl3ei12dbfwtaluyr32u7&dl=0) - Screenshot of the cyclic Item User's GUI and settings used.
[Fake Player Instructions](https://www.dropbox.com/scl/fi/pmynmdo7vl81daorkp3c7/Allow-fake-players-instructions.png?rlkey=1hg2srpj93b60lkal5gakyi35&dl=0) - Quick walkthrough of how to enable fake players (assumes FTB Teams is part of the modpack).

**Comment by penturt** [comment]
I can deal with create, but yeah once you start throwing immersive engineering and other mods you need way to much space to automate things
