### ISSUE TITLE
Some chickens recipe's are not showing up

### ISSUE THREAD

**Issue by DabTrain710** [CreeperHost/Chickens#64]
no recipe for sand or flint showing. I am wondering what other download ill need to get all the recipe's i have added 1.19.2 chickens to All the mods 8 with the polylib 1900. what else is needed?

**Comment by xaelith** [comment]
You'll need to create a datapack or use kubejs to add the crafting recipe, as it doesn't exist by default. You can also travel to a previously unexplored area, and the sand and flint chickens should spawn.

**Comment by gigabit101** [comment]
^ Sand and flint chickens spawn in the world and do no have/need recipes
