### ISSUE TITLE
What is main_chickens.cfg used for?

### ISSUE THREAD

**Issue by Waterspark63** [CreeperHost/Chickens#67]
I was looking in `https://github.com/CreeperHost/Chickens/blob/master/src/main/java/net/creeperhost/chickens/config/ConfigHandler.java`, and I noticed on line 21, there is a variable called ChickensMainFile, with the filename `main_chickens.cfg`

It's not something that normally generates, so is it used, or is it something unused as of now?
Also, I was attempting to rewrite the chickens.json for my modpack, do I have to have every property for it not to crash, or is it not supposed to crash if you skip parents for example?

**Comment by xaelith** [comment]
My guess about the main_chickens.cfg file is it's an old reference holdover from when the mod was written for an older version of Minecraft.

As for the chickens.json, not every property needs to be populated. Crashes could be from an improper syntax, such as a missing bracket or comma. I had a similar issue when trying to get fluid chickens working until I compared an older, working version of the file to the one I was working on.

**Comment by Waterspark63** [comment]
Alright, thank you! Also! Do you know if you can put a tag for the lay/drop items (i.e forge:ingots/tin), or do you have to specify a singular item?

**Comment by xaelith** [comment]
Tags should work. I was able to add a fluid egg that places a bucket of Industrial Foregoing mob essence.
