### ISSUE TITLE
Chickens 2 Feature request (1.20.4) Jade Support

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/Chickens#74]
jade does not seem to be working with the chickens mod. We aren't able to see when the chickens will have their next drop or when they are able to breed again. It would be nice if this support could be added. Thanks!

**Comment by gigabit101** [comment]
Working fine in dev
![image](https://github.com/CreeperHost/Chickens/assets/5615438/0723eb3d-68e8-4d07-83fa-e805e8c9dc32)

**Comment by gigabit101** [comment]
not an us issue, fixed in newer builds of Jade
