### ISSUE TITLE
Neoforge 1.20.4 Egg cracker uses energy regardless of operation status

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/Chickens#78]
Turning the egg cracker to redstone control it no longer proceses eggs but the energy buffer continues to drain as if it were in operation.

https://github.com/CreeperHost/Chickens/assets/9200909/297a5655-a19b-45ad-ae6b-2158fd627c94

**Comment by gigabit101** [comment]
Fixed in 2.0.5
