### ISSUE TITLE
In world resources invalidate breeder/egg cracker 

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/Chickens#79]
Presently if you have your chickens in world, redstone for example, you go back to the age old lag problem of stuffing 200 redstone chickens in a single block and collecting tons and tons of redstone. This has no material or energy cost of using the egg crackers and the chickens lifespans dont decay so you never need to breed more, you're also not constantly spending seeds on breeding eggs to crack for resources so presently there is every reason to spam entities and no value in using the machines to produce resources.

As an aside, the seed rate for eggs feels a bit high for constant egg production. If it were for breeding more chickens 1 seed for to breed them seems fine, for resource production this is way too high meaning you have to spam lots and lots of fields of wheat to keep up with the seed demand (again a non issue if you're letting them run wild)

**Comment by ThePaul-T** [comment]
Will be making some changes, most of these are bugs/oversights, so will be resolved :)

**Comment by gigabit101** [comment]
Fixed in 2.0.5
