### ISSUE TITLE
String chickens gives spider eyes and not string

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/Chickens#81]
Not sure if this is intentional or not but present the string chicken egg gives spiders eyes and not string. Might be worth renaming it to someting else if the spider eyes are the primary expected drop.

**Comment by gigabit101** [comment]
How did I manage this... https://github.com/CreeperHost/Chickens/blob/dev/1.20.4/common/src/main/java/net/creeperhost/chickens/init/ModChickens.java#L72

**Comment by gigabit101** [comment]
Fixed in 2.0.7
